const TIPOS_EVENTO = Object.freeze({
    VENDA_FINALIZADA: 'VENDA_FINALIZADA',
    VENDA_CANCELADA: 'VENDA_CANCELADA',
    RECEBIMENTO_APROVADO: 'RECEBIMENTO_APROVADO',
    COMPRA_CANCELADA: 'COMPRA_CANCELADA',
    PAGAMENTO_CONFIRMADO: 'PAGAMENTO_CONFIRMADO',
    PAGAMENTO_ESTORNADO: 'PAGAMENTO_ESTORNADO',
    DEVOLUCAO_FORNECEDOR: 'DEVOLUCAO_FORNECEDOR'
});

const STATUS_EVENTO = Object.freeze({
    PENDENTE: 'PENDENTE',
    PROCESSANDO: 'PROCESSANDO',
    PROCESSADO: 'PROCESSADO',
    ERRO: 'ERRO'
});

module.exports = { TIPOS_EVENTO, STATUS_EVENTO };
